#!/bin/bash 
#
# Pratham Kwatra
# 9/10/2020 [DATE/MONTH/YEAR]
# 
# Platform: Linux tux1 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
# 
# EDITOR: tabs=3, cols=120 (checked with echo $COLUMNS)  
#	
# OrganizeMusic file
#

debugOn="n"

read -p "Do you want to see the script as it executes? (y/[n]) => " \
   debugOn
if [ "$debugOn" == "y" -o "$debugOn" == "Y" ] ; then
	set -x      # very useful switch to the set command
fi

echo "Hello $USER"


ArtistDirCreate()
{
	   artist_name=$1
	   mkdir "$artist_name"
	   for file in *;
		   do
	      if  [ "$artist_name" == "${file%% -*}" -a "mp3" == "${file##*.}" -a -f "$file" ]; then
				newSongName=${file#* - }
				mv "$file" "$newSongName"
				mv "$newSongName" "$artist_name"; fi
		done
	}


while true; 
	do
		mp3files=$(ls *.mp3 )
		exitStatus=$?
		if [ $exitStatus -eq 0 ]; then
			artist_name=${mp3files%% -*}
			ArtistDirCreate "$artist_name"
		else
		echo "No .mp3 files left"
		break
		fi
	done
